---
settings:
  name: Astra Automation 21.12
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '21.12'
    url: "/astra-automation-2112"
  - version-number: '23.10'
    url: "/astra-automation"
  - version-number: '23.07'
    url: "/astra-automation-2307"
  - version-number: '23.04'
    url: "/astra-automation-2304"
  - version-number: '22.11'
    url: "/astra-automation-2211"
  - version-number: '22.08'
    url: "/astra-automation-2208"
  - version-number: '22.04'
    url: "/astra-automation-2204"
  - version-number: '21.08'
    url: "/astra-automation-2108"
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione di Astra Control Automation 21.12
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - section: rest-core
  - section: additional
  - section: endpoints
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: Versioni precedenti
    url: "/aa-earlier-versions.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Introduzione
      summary: Ottieni una panoramica dell'API Astra REST.
      url: "/intro/introduction.html"
    - title: Prima di iniziare
      summary: Prepararsi a iniziare a utilizzare l'API REST.
      url: "/get-started/before_get_started.html"
    - title: Ottieni un token API
      summary: Generare un token necessario per accedere all'API.
      url: "/get-started/get_api_token.html"
    - title: Ciao mondo
      summary: Verificare l'accesso di base all'API REST.
      url: "/get-started/hello_world.html"
  - title: Implementazione REST
    links:
    - title: Servizi web REST
      summary: Comprendere le basi tecnologiche dei servizi web REST.
      url: "/rest-core/rest_web_services.html"
    - title: Dettagli HTTP
      summary: Esaminare i dettagli dell'implementazione HTTP.
      url: "/rest-core/http_details.html"
    - title: Formato URL
      summary: Comprendere il formato URL e come è composto da più valori.
      url: "/rest-core/url_format.html"
  - title: Considerazioni aggiuntive
    links:
    - title: Sicurezza
      summary: Esplora la sicurezza fornita con L'API REST.
      url: "/additional/security.html"
    - title: Utilizzo delle raccolte
      summary: Utilizzare i parametri di query per accedere alle raccolte di risorse.
      url: "/additional/working_with_collections.html"
    - title: Diagnostica e supporto
      summary: Prepararsi a supportare le applicazioni Astra.
      url: "/additional/diagnostics_support.html"
  - title: Risorse
    links:
    - title: Risorse e raccolte
      summary: Acquisire familiarità con la progettazione delle risorse E delle raccolte
        REST.
      url: "/rest-core/resources_collections.html"
    - title: Risorse API REST di Astra Control
      summary: Esaminate una breve introduzione alle varie risorse Astra.
      url: "/endpoints/resources.html"
  - title: Flussi di lavoro
    links:
    - title: Preparazione
      summary: Preparati a utilizzare i flussi di lavoro Astra.
      url: "/get-started/prepare_to_use_workflows.html"
    - title: Flussi di lavoro dell'infrastruttura
      summary: I flussi di lavoro necessari per mantenere l'infrastruttura runtime
        Astra.
      url: "/workflows_infra/workflows_infra_before.html"
    - title: Workflow di gestione
      summary: I flussi di lavoro comuni utilizzati per amministrare le applicazioni
        gestite.
      url: "/workflows/workflows_before.html"
  - title: Python
    links:
    - title: Prima di iniziare
      summary: Preparatevi ad eseguire gli script Python di esempio.
      url: "/python/python_before.html"
    - title: Elencare le applicazioni gestite
      summary: Eseguire uno script di esempio per elencare le applicazioni gestite.
      url: "/python/py_list_man_apps.html"
product-family:
  name: Astra
  repo: astra-family
