---
sidebar: sidebar 
permalink: get-started/before_get_started.html 
keywords:  
summary:  
---
= Prima di iniziare
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi prepararti rapidamente a iniziare a utilizzare l'API REST di Astra Control seguendo i passaggi descritti di seguito.

.Esaminare i concetti DI REST e l'implementazione
Assicurarsi di rivedere link:../rest-core/rest_web_services.html["Implementazione core REST"] Per informazioni sui concetti REST e sui dettagli relativi alla progettazione dell'API REST di Astra Control.

.Disporre delle credenziali dell'account Astra
Per accedere all'interfaccia utente web Astra e generare un token API, sono necessarie le credenziali Astra. Con Astra Control Center, queste credenziali vengono gestite in locale. Con Astra Control Service le credenziali dell'account vengono gestite dal servizio *Auth0*.

.Ulteriori informazioni
È necessario conoscere le risorse informative aggiuntive come suggerito in link:../information/additional_resources.html["Risorse aggiuntive"].
